### PR TITLE
Bump phpstan level 6 and add a lot of next major comments

### PR DESCRIPTION
**Pull request by VincentLanglet**
Must be merged before the next release since I added some typehint/final keyword missing on the new added classes.

### CODE REVIEW

**Comment by Hanmac** [comment]
i wanted to make an MR to remove the templating stuff in 3.x
should i wait until this one is merged into 2.x ?

**Comment by VincentLanglet** [comment]
> i wanted to make an MR to remove the templating stuff in 3.x should i wait until this one is merged into 2.x ?

Will be better after this merge and the next release. This way we won't have conflict indeed.

**Review by jordisala1991 — APPROVED** [review]

**Comment by Hanmac** [comment]
@VincentLanglet can you merge this in the 3.x branch?

**Comment by VincentLanglet** [comment]
> @VincentLanglet can you merge this in the 3.x branch?

Done.

**Pull request merged**
