### PR TITLE
Next major

### PR DESCRIPTION
**Pull request by greg0ire**

### CODE REVIEW

**Comment by OskarStark** [comment]
@greg0ire StyleCI is stuck an can you change the commit message accordingly to the others i recently merged?

thank you 👍

**Comment by greg0ire** [comment]
Same here, it's "Add missing NEXT_MAJOR tag"… what's the deal?

**Comment by OskarStark** [comment]
> Same here, it's "Add missing NEXT_MAJOR tag"… what's the deal?

sorry you're right...

**Comment by greg0ire** [comment]
Build unstuck, thanks to @Soullivaneuh , please review @sonata-project/contributors

**Comment by greg0ire** [comment]
Sure

**Comment by greg0ire** [comment]
ping @sonata-project/contributors

**Pull request merged**
