### PR TITLE
Allow Twig 2.0

### PR DESCRIPTION
**Pull request by greg0ire**
I am targetting this branch, because this is supposed to be BC.

## Changelog

```markdown
### Added
- Compatibility with Twig 2.0
```

## Subject

Twig 2.0 is out, let's allow it.

### CODE REVIEW

**Comment by ickbinhier** [comment]
and make a new release please.

**Comment by OskarStark** [comment]
@greg0ire minor or patch?

**Comment by greg0ire** [comment]
@Soullivaneuh and I disagree on this. What do you think @core23 @OskarStark?

**Comment by Soullivaneuh** [comment]
We used to release a patch for this kind of modification under sonata AFAIK.

We should keep the same way.

**Comment by greg0ire** [comment]
Ok, let's use. Would be happy to have your opinion anyway @core23 @OskarStark . You know, for science. I personally think it should depend on the `composer.json` file : if the constraint is loosened to allow Twig 2.0, then nothing was broken and the new feature is compatibility with Twig 2.0, so it should be minor. If the constraint was already allowing Twig 2.0 , but it does not work and we fix it, then it should be patch.

**Comment by OskarStark** [comment]
IMO supporting a new major of a vendor is a minor and not a patch

**Comment by core23** [comment]
IMHO patch is only for bugfixes. Support for a new major dependency is a feature.

**Comment by ickbinhier** [comment]
Support for symfony 3 was released as patch in version 2.2.4

**Comment by greg0ire** [comment]
¯\_(ツ)_/¯

**Pull request merged**
