### PR TITLE
Travis cache improve

### PR DESCRIPTION
**Pull request by Soullivaneuh**
@rande To get it working, please do the following:

* Create a private token for Travis under sonata-project organisation
* Add `GITHUB_OAUTH_TOKEN` on Travis project with the containing key. The env is set to secure as default.
* Run again Travis to get it working well.

If this approach looks good, This could be added on another sonata repositories. :+1: 

Please note: When you generate the key, **save the content elsewhere** in order to configure it on another Travis project. This will avoid to create a GitHub key for each project.

### CODE REVIEW

**Comment by rande** [comment]
done... the build is in progress

**Comment by rande** [comment]
@Soullivaneuh token are not private ;)

**Comment by Soullivaneuh** [comment]
@rande Travis seems to not take care of your settings for old PR: https://travis-ci.org/sonata-project/SonataIntlBundle/jobs/66361188

Maybe on master?

**Comment by Soullivaneuh** [comment]
> @Soullivaneuh token are not private ;)

What did you mean? I see no oauth token at all on the build.

**Comment by rande** [comment]
check line 104 on https://travis-ci.org/sonata-project/SonataIntlBundle/jobs/66361188

**Comment by Soullivaneuh** [comment]
Not normal, I don't have this on my Travis: https://travis-ci.org/Soullivaneuh/IsoCodesValidator/jobs/65915505#L106

And it's exported here: https://travis-ci.org/Soullivaneuh/IsoCodesValidator/jobs/65915505#L83

Not on your.

I think I found why, just let me try.

**Comment by rande** [comment]
@Soullivaneuh Aslo, from travis-ci documentation: 

``
Similarly, we do not provide these values to untrusted builds, triggered by pull requests from another repository.

As an alternative to the web interface, you can also use the CLI’s env command.
``

This will not work for PR, and so will fail. right?

**Comment by Soullivaneuh** [comment]
Indeed! Because user can make a PR with a `echo $TOKEN` inside and then get the token.

Well. If you want to test it anymore, reset the token (because it's reveled now :-P) and merge it on master.

Revert it if does not work.

But indeed, the dist download will not work on PR. **BUT**, global composer cache will do so it's still an advantage in any way.

**Comment by rande** [comment]
@Soullivaneuh the question is why the vendor folder cannot be cached ? composer will only clone/fetch repositories when required . did I missed something ?

**Comment by Soullivaneuh** [comment]
> composer will only clone/fetch repositories when required

It should. But seems to not work on update. Example here: https://travis-ci.org/sonata-project/SonataAdminBundle/jobs/66342366#L104

With my method, all packages are re-installed but from global cache: https://travis-ci.org/Soullivaneuh/IsoCodesValidator/jobs/65915512#L117

**Pull request closed without merging**
