### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by jordisala1991**
Fix the build for github actions, not sure if it will break the travis one. To me it was due to a bug on php that is already solved

### CODE REVIEW

**Review by VincentLanglet — APPROVED** [review]

**Comment by jordisala1991** [comment]
Should we wait until we remove require for travis to merge this?

**Comment by greg0ire** [comment]
Yes, probably.

**Comment by jordisala1991** [comment]
Not sure how to ensure expected behavior avoiding this bug on all platforms

**Comment by greg0ire** [comment]
I would skip the test if a buggy version of `libicu` is detected.

**Comment by jordisala1991** [comment]
I will open an issue about it, so we dont lose the track

**Comment by phansys** [comment]
I'm not sure if this is related, but just for the records: https://github.com/sonata-project/SonataIntlBundle/pull/302#issuecomment-659099369.

**Comment by jordisala1991** [comment]
You can try to rebase to see how it looks like with github actions

**Pull request merged**
