### PR TITLE
Fix php8 build

### PR DESCRIPTION
**Pull request by jordisala1991**
## Subject

I am targeting this branch, because this is BC.

## Changelog

```markdown
### Fixed
- Fixed compatibility with php8
```

### CODE REVIEW

**Review by VincentLanglet — APPROVED** [review]

**Review by greg0ire — COMMENTED** [review]
Why does this fix the build?

**Comment by jordisala1991** [comment]
I think it is because on PHP8, the named arguments thing makes everything more strict, and the IntlDateFormatter class have the paramaters with case: https://github.com/php/php-src/blob/master/ext/intl/dateformat/dateformat.stub.php#L11

**Comment by greg0ire** [comment]
Looks like you are correct: https://3v4l.org/dnopn

**Comment by greg0ire** [comment]
I squashed and explained it in the commit message, thanks!

**Pull request merged**
