### PR TITLE
Remove exceptions from phpunit whitelists

### PR DESCRIPTION
**Pull request by jordisala1991**
I am targeting this branch, because this is pedantic.

## Subject

I think coverage is not calculated correctly, lets see

### CODE REVIEW

**Comment by OskarStark** [comment]
Do we need this for the other bundles, too?

**Comment by jordisala1991** [comment]
I did some PR already on other bundles. I will check if there is any other bundle needing this

**Comment by OskarStark** [comment]
@jordisala1991 did you checked all bundles or can you create a list in dev-kit, so I can support you applying this across all of our bundles

**Comment by jordisala1991** [comment]
I didn't checked all bundles, will create a list on dev-kit tonight :)

Maybe there are 2 or 3 that haven't been changed.

**Comment by OskarStark** [comment]
Cool, thank you in advance 👍

**Pull request merged**
